services:
  tailwind:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npx tailwindcss -i ./queuesmart/static/src/input.css -o ./queuesmart/static/src/output.css"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: queuesmart_dev
    environment:
      - DJANGO_SETTINGS_MODULE=queuesmart.settings.development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - tailwind
    command: sh -c "python manage.py runserver 0.0.0.0:8000"